on:
  workflow_call:
    inputs:
      repository:
        description: 'The repository to checkout'
        type: string
        default: '${{ github.repository }}'
      ref:
        description: 'The commit reference to checkout'
        type: string
        default: '${{ github.ref }}'
      working-directory:
        description: 'The directory the shiny app is located in within your repository'
        type: string
        default: './'
      rsconnect-app-name:
        description: 'The name of the app to deploy'
        type: string
        required: true
      environment:
        description: 'The environment to run the workflow'
        type: string
        required: true
      environment-url:
        description: 'The URL for the environment'
        type: string
      rsconnect-account-name:
        description: 'The account name for publishing'
        type: string
        required: true
      install-package:
        description: 'Whether or not this git package needs to be installed for the shiny app to work'
        type: boolean
        default: false
      renvironment-contents:
        description: 'The contents of a .Renvironment file to be stored in the root directory of the shiny app'
        type: string
        required: false
    secrets:
      rsconnect-account-token:
        description: 'The token for publishing to ShinyApps.io'
        required: true
      rsconnect-account-secret:
        description: 'The secret for publishing to ShinyApps.io'
        required: true

name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
      url: https://${{ inputs.rsconnect-account-name }}.shinyapps.io/${{ inputs.rsconnect-app-name }}
    env:
      SHINY_ACC_NAME: ${{ inputs.rsconnect-account-name }}
      SHINY_APP_NAME: ${{ inputs.rsconnect-app-name }}
      TOKEN: ${{ secrets.rsconnect-account-token }}
      SECRET: ${{ secrets.rsconnect-account-secret }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: '${{ inputs.repository }}'
          ref: '${{ inputs.ref }}'
      - name: Setup .Renvironment
        if: inputs.renvironment-contents
        run: |
          cat <<EOF > .Renviron
          ${{ inputs.renvironment-contents }}
          EOF
        shell: bash
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            rsconnect
            devtools
      - name: Install package
        if: inputs.install-package
        run: |
          pak::pkg_install("github::${{ inputs.repository }}@${{ inputs.ref }}")
        shell: Rscript {0}
      - name: Deploy to ShinyApps.io
        working-directory: ${{ inputs.working-directory }}
        run: |
          library(rsconnect)
          setAccountInfo(name = Sys.getenv("SHINY_ACC_NAME", unset = NA), token = Sys.getenv("TOKEN", unset = NA), secret = Sys.getenv("SECRET", unset=NA))
          deployApp(appName = Sys.getenv("SHINY_APP_NAME", unset = NA))
        shell: Rscript {0}